
# Trigger Action again
name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "check before"
        run : ls


      -  uses: actions/checkout@v3

      - name: "LOGIN TO DOCKER "
        run : docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: "build docker image"
        run : docker build -t ${{ secrets.DOCKER_USERNAME }}/yusuf-ahmed-2023040409 .

      - name: "build docker image"
        run : docker push ${{ secrets.DOCKER_USERNAME }}/yusuf-ahmed-2023040409

        
